'use server';

import { resolveWeekContext } from '@/lib/plans/week-context';
import { distributeEventsByDay } from '@/lib/plans/distribute-events';
import { getActivitiesInRange, aggregateWeekStats } from '@/lib/analysis/week-queries';
import { evaluateWeek, type WeekCompliance, type DayCompliance } from '@/lib/analysis/compliance';
import type { Activity } from '@/lib/db/schema';
import {
  getPlanPeriodsInRange,
  resolvePlanPeriod,
  type PlanPeriodResolved,
} from '@/lib/plans/plan-periods';
import { renderBaseMaintenanceWeek } from '@/lib/plans/base-maintenance';
import type { WeekTemplate, PlanParams } from '@/lib/plans/types';

/**
 * Serialisable shape returned to the client. Same as the server-side
 * MatrixRowData but explicitly ready to cross the wire — no functions,
 * no class instances, just pure data the React Server Action protocol
 * can transmit safely.
 */
export interface SerializedMatrixRow {
  weekStartIso: string;
  programWeekNumber: number | null;
  dojo: string | null;
  template: WeekTemplate | null;
  totalActualKm: number | null;
  totalKmTarget: number | null;
  isPast: boolean;
  /** Per-day compliance ('hit' | 'soft' | 'miss' | 'planned' | null), indexed Mon..Sun. */
  dayCompliance?: ('hit' | 'soft' | 'miss' | 'planned' | null)[];
  /** Week-level compliance pct (0-100), null when no scheduled sessions. */
  weekCompliancePct?: number | null;
  /**
   * Per-day actual activities, indexed Mon..Sun. Each entry lists every
   * Strava activity recorded on that day, ordered chronologically.
   * Structurally compatible with DayActual[] from matrix-cells.tsx.
   */
  dayActuals?: (SerializedDayActual[] | null)[];
  /** True when template was generated by base-maintenance rather than a coached plan. */
  isBaseMaintenance?: boolean;
  /**
   * Per-day calendar events, indexed Mon..Sun. Structurally compatible
   * with DayEvent[] from lib/plans/distribute-events.ts. Multi-day
   * events appear on every day they cover within the week.
   */
  dayEvents?: (SerializedDayEvent[] | null)[];
}

export interface SerializedDayActual {
  sportType: string | null;
  distanceKm: number | null;
  movingTimeS: number | null;
  paceSpk: number | null;
  name: string | null;
  startTimeHm: string;
}

export interface SerializedDayEvent {
  type: 'sickness' | 'holiday' | 'work-trip' | 'other';
  notes?: string;
  startDate: string;
  endDate: string;
}

export interface LoadResult {
  rows: SerializedMatrixRow[];
  hasMore: boolean;
}

/**
 * Lazy-load N rows in either direction relative to an anchor Monday.
 *
 * direction='past'    — newest-first ordering, page 0 = weeks [-9..-2]
 * direction='forward' — chronological ordering, page 0 = weeks [+2..+9]
 *
 * `anchorIso` is the Monday of the visible-strip's pivot — i.e. the
 * current week's Monday. Visible strip occupies offsets [-1, 0, +1];
 * lazy past starts at -2 going back, lazy forward at +2 going forward.
 */
export async function loadMatrixRows(
  direction: 'past' | 'forward',
  anchorIso: string,
  pageOffset: number = 0
): Promise<LoadResult> {
  const PAGE_SIZE = 8;
  const anchor = new Date(anchorIso + 'T00:00:00');
  const mondays: Date[] = [];

  if (direction === 'past') {
    // Page 0 → offsets [-9..-2], page 1 → [-17..-10], etc.
    const startOffset = -(2 + PAGE_SIZE - 1) - PAGE_SIZE * pageOffset;
    const endOffset = -2 - PAGE_SIZE * pageOffset;
    for (let off = startOffset; off <= endOffset; off++) {
      const m = new Date(anchor);
      m.setDate(m.getDate() + 7 * off);
      mondays.push(m);
    }
    // Newest-first when displaying past
    mondays.reverse();
  } else {
    // Page 0 → offsets [+2..+9], page 1 → [+10..+17]
    const startOffset = 2 + PAGE_SIZE * pageOffset;
    const endOffset = 9 + PAGE_SIZE * pageOffset;
    for (let off = startOffset; off <= endOffset; off++) {
      const m = new Date(anchor);
      m.setDate(m.getDate() + 7 * off);
      mondays.push(m);
    }
  }

  const rows = await buildSerializedRows(mondays);

  // Cap pages back to 12 (96 weeks ~ 22 months) and forward to 12.
  // Beyond that we're past any reasonable training history / horizon.
  const hasMore = pageOffset < 11;

  return { rows, hasMore };
}

async function buildSerializedRows(weekMondays: Date[]): Promise<SerializedMatrixRow[]> {
  if (weekMondays.length === 0) return [];

  const today = new Date().toISOString().slice(0, 10);

  // Periods covering this range, fetched once
  const fromIso = weekMondays[0].toISOString().slice(0, 10);
  const lastSunday = new Date(weekMondays[weekMondays.length - 1]);
  lastSunday.setDate(lastSunday.getDate() + 6);
  const toIso = lastSunday.toISOString().slice(0, 10);

  const periods = await getPlanPeriodsInRange(fromIso, toIso);

  // Resolve each period once
  const resolvedCache = new Map<number, PlanPeriodResolved | null>();
  async function resolveOnce(p: typeof periods[number]): Promise<PlanPeriodResolved | null> {
    if (resolvedCache.has(p.id)) return resolvedCache.get(p.id)!;
    const r = await resolvePlanPeriod(p);
    resolvedCache.set(p.id, r);
    return r;
  }

  const rows: SerializedMatrixRow[] = [];

  for (const weekStart of weekMondays) {
    const weekEnd = new Date(weekStart);
    weekEnd.setDate(weekEnd.getDate() + 6);
    const weekStartIso = weekStart.toISOString().slice(0, 10);
    const weekEndIso = weekEnd.toISOString().slice(0, 10);

    const isPast = weekEndIso < today;

    const period = periods.find((p) => {
      if (weekStartIso < p.startDate) return false;
      if (p.endDate && weekStartIso > p.endDate) return false;
      return true;
    });

    let template: WeekTemplate | null = null;
    let programWeekNumber: number | null = null;
    let dojo: string | null = null;
    let totalActualKm: number | null = null;
    let totalKmTarget: number | null = null;
    let dayCompliance: ('hit' | 'soft' | 'miss' | 'planned' | null)[] | undefined = undefined;
    let weekCompliancePct: number | null = null;
    let isBaseMaintenance = false;

    const weekContext = await resolveWeekContext({ weekStartIso, weekEndIso });
    const dayEvents = distributeEventsByDay(weekContext.events, weekStartIso);

    if (period) {
      dojo = period.dojo;
      const periodStart = new Date(period.startDate + 'T00:00:00');
      const diffDays = Math.floor(
        (weekStart.getTime() - periodStart.getTime()) / 86400000
      );
      const wkNum = Math.floor(diffDays / 7) + 1;

      if (wkNum >= 1 && wkNum <= period.programWeeks) {
        const resolved = await resolveOnce(period);
        if (resolved) {
          template = resolved.engine.renderWeek(resolved.params, wkNum, weekContext);
          programWeekNumber = wkNum;
          totalKmTarget = template.totalKmTarget;
        }
      }
    }

    // Base-maintenance fallback (mirrors program-matrix.tsx — see notes
    // there for rationale)
    if (!template) {
      const baseRefs = await resolveBaseMaintenanceReferences({
        weekStartIso,
        periods,
      });
      if (baseRefs) {
        const baseTemplate = await renderBaseMaintenanceWeek({
          weekStartIso,
          weekEndIso,
          referenceWeek1Km: baseRefs.referenceWeek1Km,
          referenceMode: baseRefs.referenceMode,
          params: baseRefs.params,
          weekNumberMarker: 0,
        });
        if (baseTemplate) {
          template = baseTemplate;
          totalKmTarget = baseTemplate.totalKmTarget;
          isBaseMaintenance = true;
        }
      }
    }

    let weekActivities: Awaited<ReturnType<typeof getActivitiesInRange>> = [];
    let dayActuals: (SerializedDayActual[] | null)[] | undefined = undefined;
    if (isPast || weekStartIso <= today) {
      weekActivities = await getActivitiesInRange(weekStartIso, weekEndIso);
      if (weekActivities.length > 0) {
        totalActualKm = aggregateWeekStats(weekActivities).totalKm;
        dayActuals = buildDayActualsSerialized(weekActivities);
      }
    }

    if (template) {
      const isFuture = weekStartIso > today;
      if (isFuture) {
        dayCompliance = buildPlannedPlaceholders(template);
      } else {
        const compliance = evaluateWeek(template, weekActivities);
        dayCompliance = buildDayComplianceArray(compliance);
        weekCompliancePct = computeWeekCompliancePct(compliance);

        if (!isPast && dayCompliance) {
          const todayDate = new Date(today + 'T00:00:00');
          for (let dow = 0; dow < 7; dow++) {
            const dayDate = new Date(weekStart);
            dayDate.setDate(dayDate.getDate() + dow);
            if (dayDate >= todayDate && dayCompliance[dow] === 'miss') {
              dayCompliance[dow] = 'planned';
            }
          }
        }
      }
    }

    rows.push({
      weekStartIso,
      programWeekNumber,
      dojo,
      template,
      totalActualKm,
      totalKmTarget,
      isPast,
      dayCompliance,
      weekCompliancePct,
      dayActuals,
      isBaseMaintenance,
      dayEvents,
    });
  }

  return rows;
}

/* Compliance reduction helpers — same logic as program-matrix.tsx,
   duplicated here so the server action is self-contained. */

function buildDayComplianceArray(weekCompliance: WeekCompliance): ('hit' | 'soft' | 'miss' | null)[] {
  const out: ('hit' | 'soft' | 'miss' | null)[] = [null, null, null, null, null, null, null];
  for (const day of weekCompliance.days) {
    out[day.dow] = reduceDayFlag(day);
  }
  return out;
}

function reduceDayFlag(day: DayCompliance): 'hit' | 'soft' | 'miss' | null {
  if (day.sessions.length === 0) return null;
  let worst: 'hit' | 'soft' | 'miss' = 'hit';
  for (const s of day.sessions) {
    const f = mapFlag(s.flag);
    if (f === 'miss') {
      worst = 'miss';
      break;
    }
    if (f === 'soft' && worst !== 'miss') worst = 'soft';
  }
  return worst;
}

function mapFlag(flag: string): 'hit' | 'soft' | 'miss' {
  switch (flag) {
    case 'ok':
      return 'hit';
    case 'warn':
    case 'fast':
    case 'slow':
    case 'short':
      return 'soft';
    case 'miss':
    case 'none':
      return 'miss';
    default:
      return 'soft';
  }
}

function computeWeekCompliancePct(weekCompliance: WeekCompliance): number | null {
  let scheduled = 0;
  let hits = 0;
  for (const day of weekCompliance.days) {
    if (day.sessions.length === 0) continue;
    scheduled++;
    const f = reduceDayFlag(day);
    if (f === 'hit') hits++;
  }
  if (scheduled === 0) return null;
  return Math.round((hits / scheduled) * 100);
}

function buildPlannedPlaceholders(template: WeekTemplate): ('hit' | 'soft' | 'miss' | 'planned' | null)[] {
  const out: ('hit' | 'soft' | 'miss' | 'planned' | null)[] = [null, null, null, null, null, null, null];
  for (const day of template.days) {
    if (day.sessions.length > 0) {
      out[day.dow] = 'planned';
    }
  }
  return out;
}

/**
 * Group week activities by day-of-week into a 7-slot array.
 *
 * Server-action mirror of buildDayActuals in program-matrix.tsx — kept
 * self-contained here because 'use server' files can only export async
 * functions, so we duplicate this small helper rather than import it.
 *
 * Returns a serialisable shape (no Date objects, no class instances)
 * suitable for crossing the server-action wire to the client.
 */
function buildDayActualsSerialized(
  activities: Activity[]
): (SerializedDayActual[] | null)[] {
  const slots: (SerializedDayActual[] | null)[] = [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ];

  for (const a of activities) {
    const d = new Date(a.startDateLocal);
    const dow = (d.getDay() + 6) % 7; // Mon=0..Sun=6

    const distanceKm =
      a.distanceM != null && a.distanceM > 0 ? a.distanceM / 1000 : null;
    const paceSpk =
      a.avgSpeedMs != null && a.avgSpeedMs > 0 ? 1000 / a.avgSpeedMs : null;

    const hh = d.getHours().toString().padStart(2, '0');
    const mm = d.getMinutes().toString().padStart(2, '0');

    const entry: SerializedDayActual = {
      sportType: a.sportType ?? a.type ?? null,
      distanceKm,
      movingTimeS: a.movingTimeS,
      paceSpk,
      name: a.name,
      startTimeHm: `${hh}:${mm}`,
    };

    if (slots[dow] === null) slots[dow] = [];
    slots[dow]!.push(entry);
  }

  for (let dow = 0; dow < 7; dow++) {
    if (slots[dow]) {
      slots[dow]!.sort((x, y) => x.startTimeHm.localeCompare(y.startTimeHm));
    }
  }

  return slots;
}

/* ----------------------------------------------------------------------------
 * Base-maintenance reference resolver — mirror of the helper in
 * program-matrix.tsx. Action files must be self-contained (only async
 * exports allowed at the top), so duplication here is preferred over
 * an import that would create a cross-file 'use server' tangle.
 * ------------------------------------------------------------------------- */
async function resolveBaseMaintenanceReferences({
  weekStartIso,
  periods,
}: {
  weekStartIso: string;
  periods: Awaited<ReturnType<typeof getPlanPeriodsInRange>>;
}): Promise<{
  referenceWeek1Km: number | null;
  referenceMode: 'pre-program' | 'post-program' | 'no-program';
  params: PlanParams | null;
} | null> {
  if (periods.length === 0) {
    return {
      referenceWeek1Km: null,
      referenceMode: 'no-program',
      params: null,
    };
  }

  const upcoming = periods.find((p) => p.startDate > weekStartIso);
  const ended = periods
    .filter((p) => p.endDate !== null && p.endDate < weekStartIso)
    .sort((a, b) => (b.endDate ?? '').localeCompare(a.endDate ?? ''))[0];

  if (upcoming) {
    const resolved = await resolvePlanPeriod(upcoming);
    if (!resolved) {
      return {
        referenceWeek1Km: null,
        referenceMode: 'pre-program',
        params: null,
      };
    }
    let week1Km: number | null = null;
    try {
      const week1Template = resolved.engine.renderWeek(resolved.params, 1, {
        weekStartIso: upcoming.startDate,
        weekEndIso: upcoming.startDate,
        goalRace: null,
        tuneupRaces: [],
        recurringSessions: [],
        events: [],
        ninjaLoopDays: [],
      });
      week1Km = week1Template.totalKmTarget;
    } catch {
      // Engine couldn't render without proper context — leave null
    }
    return {
      referenceWeek1Km: week1Km,
      referenceMode: 'pre-program',
      params: resolved.params,
    };
  }

  if (ended) {
    const resolved = await resolvePlanPeriod(ended);
    return {
      referenceWeek1Km: null,
      referenceMode: 'post-program',
      params: resolved?.params ?? null,
    };
  }

  return {
    referenceWeek1Km: null,
    referenceMode: 'no-program',
    params: null,
  };
}
